env:
  browser: true
  es2020: true
  jest/globals: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:jest/recommended'
  - 'plugin:react-hooks/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
  - jest
rules: 
  react/prop-types: off
  react/display-name: off

